# Generated by Django 5.2.12 on 2026-03-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredients_recipe'),
    ]

    operations = []
